In [1]:
import numpy as np

In [2]:
## N training examples
## M features

X = np.array([
    [1.2, 3.1],
    [1.5, 2.8],
    [1.1, 3.3],
    [4.0, -1.2],
    [4.2, -1.0],
    [3.8, -0.8],
    [-2.5, 4.0],
    [-2.3, 4.2],
    [-2.6, 3.8],
    [-2.4, 4.1]
])

y = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])
print(X)
print("")
print(y)

[[ 1.2  3.1]
 [ 1.5  2.8]
 [ 1.1  3.3]
 [ 4.  -1.2]
 [ 4.2 -1. ]
 [ 3.8 -0.8]
 [-2.5  4. ]
 [-2.3  4.2]
 [-2.6  3.8]
 [-2.4  4.1]]

[0 0 0 1 1 1 2 2 2 2]


In [3]:
n = X.shape[0]
m = X.shape[1]
classes = 3
print(n) ## No. of training examples
print(m) ## No. of features
print(classes) ## No. of classes of y

10
2
3


In [4]:
W = np.zeros((m, classes))
b = np.zeros((1, classes))
print(W)
print(W.shape)
print("")
print(b)
print(b.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)

[[0. 0. 0.]]
(1, 3)


In [5]:
def softmax(z):
  exp = np.exp(z)
  return exp/np.sum(exp, axis = 1, keepdims = True)

In [6]:
n_iterations = 1000
learning_rate = 0.1

In [7]:
for _ in range(n_iterations):
  pred = np.dot(X, W) + b
  pred = softmax(pred)

  y_true = np.zeros_like(pred)
  y_true[np.arange(n), y] = 1

  dW = (1/n) * np.dot(X.T, (pred - y_true))
  db = (1/n) * np.sum(pred - y_true, axis=0, keepdims=True)

  W -= learning_rate * dW
  b -= learning_rate * db

print(W)
print(b)

[[ 0.80790298  1.59659178 -2.40449476]
 [ 1.00277162 -1.51578546  0.51301384]]
[[-0.08670276  0.1460243  -0.05932154]]


In [8]:
y_pred = np.dot(X, W) + b
y_pred = softmax(y_pred)
np.argmax(y_pred, axis = 1)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])