In [1]:
import numpy as np

In [2]:
X = np.array([[0, 0, 0],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1],
              [0.5, 0.5, 0.5],
              [0.8, 0.2, 0.3]])

Y = np.array([[0],
              [0],
              [0],
              [1],
              [0],
              [1]])
print(X) ## NxM matrix
print("")
print(Y) ## Nx1 matrix

[[0.  0.  0. ]
 [0.  1.  1. ]
 [1.  0.  1. ]
 [1.  1.  1. ]
 [0.5 0.5 0.5]
 [0.8 0.2 0.3]]

[[0]
 [0]
 [0]
 [1]
 [0]
 [1]]


#### Implementation of Basic Perceptron

In [3]:
##Adding X0 column of ones
X = np.c_[np.ones((X.shape[0], 1)), X]
X ## NxM+1 matrix

array([[1. , 0. , 0. , 0. ],
       [1. , 0. , 1. , 1. ],
       [1. , 1. , 0. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0.5, 0.5, 0.5],
       [1. , 0.8, 0.2, 0.3]])

In [16]:
learning_rate = 0.2
n_iterations = 1000
m = X.shape[1] ##No. of features(M+1)
n = X.shape[0] ##No. of training samples(N)

In [17]:
##Initialize random weights
weights = np.random.rand(m, 1)
weights.shape ## mx1 matrix

(4, 1)

In [18]:
def perceptron_function(z):
  return np.where(z >= 0, 1, 0)

In [19]:
for _ in range(n_iterations):
  ## Batch Grad ascent
  weights = weights + learning_rate * (X.T @ (Y - (perceptron_function(X @ weights)))) ## theta = theta + alpha*((y - predicition) * X)
weights

array([[-0.66254957],
       [ 1.06566588],
       [ 0.67897172],
       [-0.44695126]])

In [20]:
predictions = X @ weights
predictions

array([[-0.66254957],
       [-0.43052911],
       [-0.04383495],
       [ 0.63513677],
       [-0.0137064 ],
       [ 0.1916921 ]])

In [21]:
predictions = (predictions >= 0.5).astype(int)
predictions

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0]])