In [1]:
import numpy as np

In [25]:
X = np.array([[1, 2, 3],
              [2, 3, 4],
              [3, 4, 5],
              [4, 5, 6],
              [5, 6, 7]])

Y = Y = np.array([[6],
              [7],
              [8],
              [9],
              [10]])
print(X)
print(Y) ## Nx1 matrix

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]
[[ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


#### Implementation of Linear Regression with minimizing Least Square error cost

In [26]:
##Adding X0 column of ones
X = np.c_[np.ones((X.shape[0], 1)), X]
X ## NxM matrix

array([[1., 1., 2., 3.],
       [1., 2., 3., 4.],
       [1., 3., 4., 5.],
       [1., 4., 5., 6.],
       [1., 5., 6., 7.]])

In [27]:
learning_rate = 0.005
n_iterations = 1000
m = X.shape[1] ##No. of features
n = X.shape[0] ##No. of training samples

In [28]:
##Initialize random weights
weights = np.random.rand(m, 1)
weights.shape ## Mx1 matrix

(4, 1)

In [29]:
for _ in range(n_iterations):
  weights = weights -  learning_rate * (X.T @ ((X @ weights) - Y)) ## theta = theta - alpha*((prediction - y) * X)
weights

array([[ 2.17145661],
       [-0.46659609],
       [ 0.10618608],
       [ 1.36069087]])

In [30]:
predictions = X @ weights
predictions

array([[ 5.99930529],
       [ 6.99958614],
       [ 7.999867  ],
       [ 9.00014786],
       [10.00042872]])