In [1]:
import numpy as np

In [32]:
X = np.array([[0, 0, 0],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1],
              [0.5, 0.5, 0.5],
              [0.8, 0.2, 0.3]])

Y = np.array([[0],
              [0],
              [0],
              [1],
              [0],
              [1]])
print(X)
print("")
print(Y) ## Nx1 matrix

[[0.  0.  0. ]
 [0.  1.  1. ]
 [1.  0.  1. ]
 [1.  1.  1. ]
 [0.5 0.5 0.5]
 [0.8 0.2 0.3]]

[[0]
 [0]
 [0]
 [1]
 [0]
 [1]]


#### Implementation of Logistic Regression with maximizing log likelihood

In [33]:
##Adding X0 column of ones
X = np.c_[np.ones((X.shape[0], 1)), X]
X ## NxM matrix

array([[1. , 0. , 0. , 0. ],
       [1. , 0. , 1. , 1. ],
       [1. , 1. , 0. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0.5, 0.5, 0.5],
       [1. , 0.8, 0.2, 0.3]])

In [51]:
learning_rate = 0.001
n_iterations = 1000
m = X.shape[1] ##No. of features
n = X.shape[0] ##No. of training samples

In [52]:
##Initialize random weights
weights = np.random.rand(m, 1)
weights.shape ## Mx1 matrix

(4, 1)

In [53]:
def sigmoid(z):
  return 1 / (1 + np.exp(-z))

In [54]:
for _ in range(n_iterations):
  ## Batch Grad ascent
  weights = weights + learning_rate * (X.T @ (Y - (sigmoid(X @ weights)))) ## theta = theta + alpha*((y - predicition) * X)
weights

array([[-0.27836175],
       [ 0.36026302],
       [-0.0531296 ],
       [-0.38798215]])

In [55]:
predictions = X @ weights
predictions

array([[-0.27836175],
       [-0.71947351],
       [-0.30608088],
       [-0.35921049],
       [-0.31878612],
       [-0.1171719 ]])

In [56]:
predictions = (predictions >= 0.5).astype(int)
predictions

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0]])