In [1]:
import numpy as np

In [3]:
## N training examples
## M features

X = np.array([[1, 4], [2, 6], [3, 8], [5, 8], [6, 10], [7, 1], [8, 2], [9, 3], [10, 4], [11, 5]])
y = np.array([1, 1, 1, 1, 1, -1, -1, -1, -1, -1])

print(X)
print("")
print(y)

[[ 1  4]
 [ 2  6]
 [ 3  8]
 [ 5  8]
 [ 6 10]
 [ 7  1]
 [ 8  2]
 [ 9  3]
 [10  4]
 [11  5]]

[ 1  1  1  1  1 -1 -1 -1 -1 -1]


In [ ]:
n = X.shape[0] ##No. of training examples
m = X.shape[1] ##No. of features

print(n)
print(m)

10
2


###### Initialize the parameters. W will be a column vector ideally with shape mX1 but can use numpy shape of (m,) and still perform matrix multiplication and b will be scalar.

In [6]:
w = np.zeros(m)
b = 0

print(w)
print(b)

[0. 0.]
0


###### Hyperparameters

In [7]:
learning_rate = 0.001
iterations = 1000

###### Defining the margin as 1 and any classified points that are not classified within the margin, the params are updated. Ideally should be w.T@X, but we can use numpy property. Calculating the hinge loss as well.
###### Parameters are updated after solving the convex optimization problem of minimizing w.

In [11]:
for j in range(iterations):
  for i in range(n):
    if y[i] * (np.dot(w, X[i]) + b) < 1:
      w += learning_rate * y[i] * X[i]
      b += learning_rate * y[i]

  if j % 100 == 0:
    margin = 1 - y * (np.dot(X, w) + b)
    hinge_loss = np.maximum(0, margin)
    loss = 0.5 * np.dot(w, w) + np.sum(hinge_loss)
    print(f"Loss: {loss}")

print("")
print(w)
print("")
print(b)

Loss: 0.07490250000000005
Loss: 0.07490250000000005
Loss: 0.07490250000000005
Loss: 0.07490250000000005
Loss: 0.07490250000000005
Loss: 0.07490250000000005
Loss: 0.07490250000000005
Loss: 0.07490250000000005
Loss: 0.07490250000000005
Loss: 0.07490250000000005

[-0.237  0.306]

0.025000000000000015


###### Predictions on the data

In [12]:
predictions = np.sign(np.dot(X, w) + b)
predictions

array([ 1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1.])