In [ ]:
import numpy as np

###### Defining the features X which need to be binary and the output Y

In [ ]:
X = np.array([[1, 0, 1],
              [1, 1, 0],
              [1, 0, 0],
              [0, 1, 1],
              [0, 1, 1],
              [1, 1, 1]])

y = np.array([0, 0, 0, 1, 1, 1])

print(X)
print("")
print(y)

[[1 0 1]
 [1 1 0]
 [1 0 0]
 [0 1 1]
 [0 1 1]
 [1 1 1]]

[0 0 0 1 1 1]


###### Phi is the probability of a positive sample in our data

In [ ]:
phi = np.mean(y == 1)
phi

0.5

###### The mean of the Xs each for Y = 0 and Y = 1. Added +1 to numerator and +2 to denominator as Laplace Smoothing

In [ ]:
phi_given_y1 = (np.sum(X[y == 1], axis = 0) + 1) / (np.sum(y == 1) + 2)
phi_given_y0 = (np.sum(X[y == 0], axis = 0) + 1) / (np.sum(y == 0) + 2)

print(phi_given_y1)
print("")
print(phi_given_y0)

[0.4 0.8 0.8]

[0.8 0.4 0.4]


###### Calculating the posterior probabilites

In [ ]:
def prediction(X):
  predictions = []

  P_x_given_y1 = np.prod(np.where(X == 1, phi_given_y1, 1 - phi_given_y1))
  P_x_given_y0 = np.prod(np.where(X == 1, phi_given_y0, 1 - phi_given_y0))

  ## Bayes' Theorum
  P_y1_given_x = P_x_given_y1 * phi
  P_y0_given_x = P_x_given_y0 * (1 - phi)

  if(P_y1_given_x > P_y0_given_x):
    return 1
  else:
    return 0

In [ ]:
X = np.array([1, 0, 1])
prediction(X)

0