In [1]:
import numpy as np

In [2]:
## N training examples
## M features

X = np.array([[1, 2, 3],
              [2, 3, 4],
              [3, 4, 5],
              [4, 5, 6],
              [5, 6, 7]])

Y = Y = np.array([[6],
              [7],
              [8],
              [9],
              [10]])
print(X)
print(Y) ## Nx1 matrix

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]
[[ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


###### X is a NxM matrix and Y is a Nx1 matrix

#### Implementation of Linear Regression with minimizing Least Square error cost

###### We add the column of X0 where all X0s are 1s to X so that the matrix multiplication in the next steps becomes easier. This makes X a NxM+1 matrix

In [3]:
X = np.c_[np.ones((X.shape[0], 1)), X]
X

array([[1., 1., 2., 3.],
       [1., 2., 3., 4.],
       [1., 3., 4., 5.],
       [1., 4., 5., 6.],
       [1., 5., 6., 7.]])

###### We set our initial learning rate. We can play around with this rate, to control the amount of gradient descent has effect on params. Larger rate makes the descent rapid but can cause cost to sway other way, where as smaller rate can cause the gradient descent steps to have very less effect.
###### We set the number of iterations as well. Can play around till the cost is minimized after a point.
###### Updated m = M+1 and n = N

In [4]:
learning_rate = 0.005
n_iterations = 1000
m = X.shape[1]
n = X.shape[0]

###### Setting the initial params values. Can set all to 0 as well.

In [5]:
weights = np.random.rand(m, 1)
weights.shape

(4, 1)

#### Stochastic Gradient Descent

###### Running stochastic gradient descent where the cost is computed for each example and then the params are updated by multiplying with the learning rate. Then this is looped for all examples.

In [6]:
for _ in range(n_iterations):
  for i in range(n):
    weights = weights -  learning_rate * (X[i].reshape(m, 1) @ ((X[i].reshape(1, m) @ weights) - Y[i].reshape(1, 1)))
weights

array([[ 1.8848451 ],
       [-0.79925266],
       [ 0.48412429],
       [ 1.31525229]])

###### The predictions given by multiplying the X and params

In [7]:
predictions = X @ weights
predictions

array([[ 5.99959789],
       [ 6.99972182],
       [ 7.99984574],
       [ 8.99996967],
       [10.00009359]])